version: '3.8'
services:
  app:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    ports:
      - "5001:5001"
    volumes:
      - ../data:/app/data
      - ../chroma_db:/app/chroma_db
    environment:
      - FLASK_ENV=development
  chromadb:
    image: chromadb/chroma:latest
    ports:
      - "8001:8001"
    volumes:
      - ../chroma_db:/chroma/chroma
  promaetheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"